# site settings
title: Joseph Marsh
subtitle: Mechanical Engineer
email: josephwmarsh@gmail.com
description: Mechanical Engineering student at Oregon State University.<br /> Portfolio showcasing thermal systems, design, and data-driven analysis.
baseurl: "" # Keep this blank so the styling works on your main github.io page
url: "https://josephwmarsh.github.io" # Your actual website link
author: Joseph Marsh
street_address: 
city: Corvallis
state: OR
zip_code: 97330
country: United States
phone: 971-666-2517

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/josephwmarsh
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/joseph-w-marsh
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
